import { StyleSheet } from 'react-native';

import { palette, radius, spacing, touchTarget, typeScale } from '../../lib/design';

export const profileStyles = StyleSheet.create({
  keyboard: { flex: 1 },
  content: { gap: spacing.lg },
  section: { gap: spacing.md },
  sectionTitle: { fontSize: typeScale.subtitle, fontWeight: '800', color: palette.ink },
  input: {
    minHeight: 50,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    fontSize: typeScale.input,
    color: palette.ink,
    backgroundColor: palette.paper,
  },
  multiline: { minHeight: 108, paddingTop: spacing.md, paddingBottom: spacing.md },
  help: { fontSize: typeScale.caption, lineHeight: 18, color: palette.muted },
  notice: { padding: spacing.md, borderRadius: radius.md, borderWidth: 1 },
  noticeSuccess: { backgroundColor: palette.mint, borderColor: palette.green },
  noticeError: { backgroundColor: palette.warningPaper, borderColor: palette.warningLine },
  noticeText: { fontSize: typeScale.body, lineHeight: 20, color: palette.ink },
  photoSection: { alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.md },
  avatar: {
    width: 104,
    height: 104,
    borderRadius: 36,
    backgroundColor: palette.mint,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 3,
    borderColor: palette.paper,
  },
  avatarImage: { width: '100%', height: '100%' },
  avatarInitials: { fontSize: 28, fontWeight: '800', color: palette.green },
  photoButton: {
    minHeight: touchTarget,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: radius.md,
    backgroundColor: palette.mint,
  },
  photoButtonText: { fontSize: typeScale.body, fontWeight: '800', color: palette.green },
  spotRow: {
    minHeight: 62,
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: palette.line,
    paddingVertical: spacing.sm,
  },
  spotLogo: {
    width: touchTarget,
    height: touchTarget,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.mint,
  },
  spotLogoSelected: { backgroundColor: palette.green },
  spotCopy: { flex: 1, marginHorizontal: spacing.md },
  spotName: { fontSize: typeScale.body, fontWeight: '800', color: palette.ink },
});
