import { StyleSheet } from 'react-native';
import { palette } from '../../lib/design';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.cream },
  scroll: { padding: 20, paddingBottom: 52 },
  header: { flexDirection: 'row', alignItems: 'center', marginBottom: 18 },
  headerTitle: { flex: 1, textAlign: 'center', color: palette.ink, fontSize: 21, fontWeight: '800' },
  iconButton: { width: 44, height: 44, borderRadius: 14, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper, alignItems: 'center', justifyContent: 'center' },
  spacer: { width: 44 },
  overline: { color: palette.green, fontSize: 10, fontWeight: '900', letterSpacing: 1.2, textTransform: 'uppercase' },
  title: { color: palette.ink, fontSize: 29, lineHeight: 35, fontWeight: '800', marginTop: 5 },
  intro: { color: palette.muted, fontSize: 14, lineHeight: 21, marginTop: 7, marginBottom: 16 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  filters: { paddingBottom: 12, gap: 8 },
  chip: { minHeight: 42, paddingHorizontal: 14, borderRadius: 14, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper, alignItems: 'center', justifyContent: 'center' },
  chipActive: { borderColor: palette.green, backgroundColor: palette.mint },
  chipText: { color: palette.muted, fontSize: 11, fontWeight: '800', textTransform: 'capitalize' },
  chipTextActive: { color: palette.green },
  actions: { flexDirection: 'row', gap: 10, marginBottom: 14 },
  primaryButton: { minHeight: 50, flex: 1, paddingHorizontal: 16, borderRadius: 16, backgroundColor: palette.green, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  primaryText: { color: palette.paper, fontSize: 13, fontWeight: '800' },
  secondaryButton: { minHeight: 50, flex: 1, paddingHorizontal: 16, borderRadius: 16, borderWidth: 1, borderColor: palette.green, backgroundColor: palette.paper, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  secondaryText: { color: palette.green, fontSize: 13, fontWeight: '800' },
  warningButton: { borderColor: palette.orange },
  warningText: { color: palette.orange },
  disabled: { opacity: 0.45 },
  card: { borderRadius: 19, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper, overflow: 'hidden', marginBottom: 12 },
  cardImage: { width: '100%', height: 165, backgroundColor: palette.mint },
  cardBody: { padding: 15 },
  cardTop: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  logo: { width: 30, height: 30, borderRadius: 10, backgroundColor: palette.mint },
  logoEmpty: { alignItems: 'center', justifyContent: 'center' },
  businessName: { flex: 1, color: palette.ink, fontSize: 12, fontWeight: '800' },
  badge: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 9, backgroundColor: palette.mint },
  badgeWarning: { backgroundColor: '#F6E3D6' },
  badgeText: { color: palette.green, fontSize: 9, fontWeight: '900', textTransform: 'uppercase' },
  cardTitle: { color: palette.ink, fontSize: 18, lineHeight: 23, fontWeight: '800' },
  excerpt: { color: palette.muted, fontSize: 13, lineHeight: 19, marginTop: 7 },
  meta: { color: palette.muted, fontSize: 11, lineHeight: 16, marginTop: 9 },
  emptyCard: { alignItems: 'center', padding: 28, borderRadius: 19, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper, marginTop: 16 },
  emptyTitle: { color: palette.ink, fontSize: 17, fontWeight: '800', marginTop: 10 },
  emptyText: { color: palette.muted, fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 6 },
  errorCard: { alignItems: 'center', padding: 22, borderRadius: 18, borderWidth: 1, borderColor: '#F0C7AD', backgroundColor: '#FFF3EA', marginTop: 12 },
  errorText: { color: palette.orange, textAlign: 'center', fontSize: 12, lineHeight: 18 },
  compactState: { minHeight: 92, alignItems: 'center', justifyContent: 'center', gap: 8, padding: 18, borderRadius: 18, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper },
  link: { color: palette.green, fontSize: 12, fontWeight: '800' },
  field: { marginTop: 15 },
  label: { color: palette.muted, fontSize: 10, fontWeight: '900', letterSpacing: 0.8, textTransform: 'uppercase', marginBottom: 7 },
  input: { minHeight: 50, borderRadius: 14, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper, color: palette.ink, paddingHorizontal: 14, fontSize: 14 },
  multiline: { minHeight: 90, paddingTop: 13, textAlignVertical: 'top' },
  editorShell: { minHeight: 240, borderRadius: 16, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper, overflow: 'hidden' },
  editor: { minHeight: 190, backgroundColor: palette.paper },
  reader: { minHeight: 180, backgroundColor: palette.cream },
  switchRow: { minHeight: 58, flexDirection: 'row', alignItems: 'center', padding: 14, borderRadius: 15, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper, marginTop: 14 },
  switchCopy: { flex: 1, paddingRight: 12 },
  switchTitle: { color: palette.ink, fontSize: 13, fontWeight: '800' },
  switchHint: { color: palette.muted, fontSize: 11, lineHeight: 16, marginTop: 3 },
  dateButton: { minHeight: 50, paddingHorizontal: 14, borderRadius: 14, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper, flexDirection: 'row', alignItems: 'center', gap: 9 },
  dateText: { flex: 1, color: palette.ink, fontSize: 13, fontWeight: '700' },
  coverPicker: { height: 190, borderRadius: 18, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.mint, overflow: 'hidden', alignItems: 'center', justifyContent: 'center' },
  coverImage: { width: '100%', height: '100%' },
  coverOverlay: { position: 'absolute', right: 10, bottom: 10, flexDirection: 'row', gap: 7 },
  overlayButton: { minHeight: 42, paddingHorizontal: 12, borderRadius: 12, backgroundColor: 'rgba(36,26,22,0.82)', flexDirection: 'row', gap: 6, alignItems: 'center' },
  overlayText: { color: palette.paper, fontSize: 10, fontWeight: '800' },
  sectionCard: { padding: 15, borderRadius: 18, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper, marginTop: 16 },
  detailHero: { width: '100%', height: 245, backgroundColor: palette.mint },
  detailBody: { padding: 20, paddingBottom: 48 },
  detailTitle: { color: palette.ink, fontSize: 30, lineHeight: 36, fontWeight: '800', marginTop: 10 },
  cancellation: { padding: 14, borderRadius: 15, backgroundColor: '#FFF3EA', borderWidth: 1, borderColor: '#F0C7AD', marginTop: 14 },
  cancellationTitle: { color: palette.orange, fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  cancellationText: { color: palette.muted, fontSize: 12, lineHeight: 18, marginTop: 4 },
  loadMore: { minHeight: 48, alignItems: 'center', justifyContent: 'center' },
  subtle: { color: palette.muted, fontSize: 11, textAlign: 'center' },
});
