import { StyleSheet } from 'react-native';

import { palette, radius, shadows, spacing, touchTarget, typeScale } from '../../lib/design';

export const categoryStyles = StyleSheet.create({
  editor: {
    padding: spacing.lg,
    marginBottom: spacing.xl,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
    ...shadows.card,
  },
  editorTitle: { color: palette.ink, fontSize: typeScale.subtitle, fontWeight: '800' },
  label: {
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
    color: palette.muted,
    fontSize: typeScale.overline,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  input: {
    minHeight: 50,
    paddingHorizontal: spacing.lg,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.nearWhite,
    color: palette.ink,
    fontSize: typeScale.input,
  },
  iconHint: { color: palette.muted, fontSize: typeScale.caption, lineHeight: 18 },
  iconGrid: { marginTop: spacing.sm, flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  iconChoice: {
    width: '31%',
    minWidth: 88,
    minHeight: 76,
    padding: spacing.sm,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.cream,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  iconChoiceSelected: { borderColor: palette.green, backgroundColor: palette.mint },
  iconChoiceText: { color: palette.muted, fontSize: 10, fontWeight: '700', textAlign: 'center' },
  iconChoiceTextSelected: { color: palette.green },
  matchCard: {
    marginTop: spacing.md,
    padding: spacing.md,
    borderRadius: radius.md,
    backgroundColor: palette.warningPaper,
    borderWidth: 1,
    borderColor: palette.warningLine,
  },
  matchTitle: { color: palette.orange, fontSize: typeScale.body, fontWeight: '800' },
  matchText: { marginTop: spacing.xs, color: palette.muted, fontSize: typeScale.caption, lineHeight: 18 },
  exactText: { marginTop: spacing.md, color: palette.orange, fontSize: typeScale.caption, lineHeight: 18 },
  checkingRow: { marginTop: spacing.sm, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  checkingText: { color: palette.muted, fontSize: typeScale.caption },
  editorActions: { marginTop: spacing.lg, gap: spacing.sm },
  banner: {
    marginBottom: spacing.lg,
    padding: spacing.md,
    borderRadius: radius.md,
    backgroundColor: palette.mint,
  },
  bannerText: { color: palette.green, fontSize: typeScale.caption, fontWeight: '700', lineHeight: 18 },
  errorBanner: { backgroundColor: palette.warningPaper, borderWidth: 1, borderColor: palette.warningLine },
  errorText: { color: palette.orange, fontSize: typeScale.caption, lineHeight: 18 },
  listHeader: {
    marginTop: spacing.xl,
    marginBottom: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  listTitle: { color: palette.ink, fontSize: typeScale.subtitle, fontWeight: '800' },
  count: { color: palette.muted, fontSize: typeScale.caption },
  row: {
    marginBottom: spacing.md,
    padding: spacing.lg,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
  },
  rowHeader: { flexDirection: 'row', alignItems: 'center' },
  rowIcon: {
    width: touchTarget,
    height: touchTarget,
    marginRight: spacing.md,
    borderRadius: radius.sm,
    backgroundColor: palette.mint,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowCopy: { flex: 1, paddingRight: spacing.md },
  rowName: { color: palette.ink, fontSize: 16, fontWeight: '800' },
  rowCount: { marginTop: spacing.xs, color: palette.muted, fontSize: typeScale.caption },
  rowActions: { marginTop: spacing.md, flexDirection: 'row', gap: spacing.sm },
  rowAction: {
    flex: 1,
    minHeight: touchTarget,
    borderRadius: radius.sm,
    backgroundColor: palette.cream,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  rowActionDanger: { backgroundColor: palette.warningPaper },
  rowActionText: { color: palette.green, fontSize: 10, fontWeight: '800' },
  rowActionDangerText: { color: palette.orange },
  disabled: { opacity: 0.42 },
});
