import { StyleSheet } from 'react-native';

import { palette } from '../../lib/design';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.cream },
  scroll: { padding: 20, paddingBottom: 48 },
  header: { flexDirection: 'row', alignItems: 'center', marginBottom: 18 },
  headerTitle: { flex: 1, textAlign: 'center', color: palette.ink, fontSize: 20, fontWeight: '800' },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconButtonDisabled: { opacity: 0.35 },
  spacer: { width: 44 },
  intro: { color: palette.muted, fontSize: 14, lineHeight: 21, marginBottom: 16 },
  actions: { flexDirection: 'row', gap: 10, marginBottom: 8 },
  primaryButton: {
    flex: 1,
    minHeight: 50,
    borderRadius: 16,
    backgroundColor: palette.green,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  primaryText: { color: palette.paper, fontSize: 13, fontWeight: '800' },
  secondaryButton: {
    flex: 1,
    minHeight: 50,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.green,
    flexDirection: 'row',
    gap: 7,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  secondaryText: { color: palette.green, fontSize: 13, fontWeight: '800' },
  disabled: { opacity: 0.5 },
  errorCard: {
    alignItems: 'center',
    padding: 24,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.warningLine,
    backgroundColor: palette.warningPaper,
    marginTop: 14,
  },
  errorText: { color: palette.orange, fontSize: 12, lineHeight: 18, textAlign: 'center' },
  retryButton: {
    minHeight: 46,
    marginTop: 12,
    paddingHorizontal: 20,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyCard: {
    alignItems: 'center',
    padding: 28,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
    marginTop: 18,
  },
  emptyTitle: { color: palette.ink, fontSize: 17, fontWeight: '800', marginTop: 10 },
  emptyText: { color: palette.muted, fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 6 },
  categoryHeader: { flexDirection: 'row', alignItems: 'center', marginTop: 24, marginBottom: 10 },
  categoryName: { flex: 1, color: palette.ink, fontSize: 18, fontWeight: '800' },
  categoryCount: { color: palette.muted, fontSize: 11, marginRight: 8 },
  compactButton: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  itemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 92,
    padding: 12,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
    marginBottom: 10,
  },
  itemPhoto: { width: 68, height: 68, borderRadius: 14, backgroundColor: palette.mint },
  itemPhotoEmpty: { alignItems: 'center', justifyContent: 'center' },
  itemBody: { flex: 1, paddingHorizontal: 12 },
  itemTop: { flexDirection: 'row', alignItems: 'center' },
  itemName: { flex: 1, color: palette.ink, fontSize: 14, fontWeight: '800' },
  itemPrice: { color: palette.green, fontSize: 13, fontWeight: '900' },
  itemDescription: { color: palette.muted, fontSize: 11, lineHeight: 16, marginTop: 4 },
  availability: {
    alignSelf: 'flex-start',
    marginTop: 7,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 9,
    backgroundColor: palette.mint,
  },
  unavailable: { backgroundColor: palette.softOrange },
  availabilityText: { color: palette.green, fontSize: 9, fontWeight: '900', textTransform: 'uppercase' },
  formCard: {
    padding: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
  },
  field: { marginTop: 15 },
  label: {
    color: palette.muted,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 7,
  },
  input: {
    minHeight: 50,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
    color: palette.ink,
    paddingHorizontal: 14,
    fontSize: 14,
  },
  multiline: { minHeight: 100, paddingTop: 13, textAlignVertical: 'top' },
  photoPicker: {
    height: 180,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.mint,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoPreview: { width: '100%', height: '100%' },
  photoOverlay: { position: 'absolute', right: 10, bottom: 10, flexDirection: 'row', gap: 7 },
  photoAction: {
    minHeight: 42,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(36,26,22,0.82)',
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoActionText: { color: palette.paper, fontSize: 10, fontWeight: '800' },
  categoryOptions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  categoryOption: {
    minHeight: 42,
    paddingHorizontal: 13,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryOptionActive: { borderColor: palette.green, backgroundColor: palette.mint },
  categoryOptionText: { color: palette.muted, fontSize: 11, fontWeight: '800' },
  categoryOptionTextActive: { color: palette.green },
  availabilityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
    marginTop: 16,
  },
  availabilityCopy: { flex: 1, paddingRight: 12 },
  availabilityTitle: { color: palette.ink, fontSize: 13, fontWeight: '800' },
  availabilityHint: { color: palette.muted, fontSize: 11, lineHeight: 16, marginTop: 3 },
  submitButton: {
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  submitText: { color: palette.paper, fontSize: 14, fontWeight: '800' },
});
