import { StyleSheet } from 'react-native';
import { palette } from '../../lib/design';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.cream }, scroll: { padding: 20, paddingBottom: 48 }, center: { flex: 1, padding: 28, alignItems: 'center', justifyContent: 'center' },
  header: { flexDirection: 'row', alignItems: 'center', marginBottom: 18 }, headerTitle: { flex: 1, textAlign: 'center', color: palette.ink, fontSize: 20, fontWeight: '800' }, iconButton: { width: 42, height: 42, borderRadius: 14, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper, alignItems: 'center', justifyContent: 'center' }, spacer: { width: 42 },
  lead: { color: palette.muted, fontSize: 14, lineHeight: 21, marginBottom: 14 }, sectionTitle: { color: palette.ink, fontSize: 17, fontWeight: '800', marginTop: 22, marginBottom: 10 },
  card: { flexDirection: 'row', alignItems: 'center', padding: 14, borderRadius: 16, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper, marginBottom: 10 }, avatar: { width: 44, height: 44, borderRadius: 14, backgroundColor: palette.mint, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }, avatarImage: { width: '100%', height: '100%' }, avatarText: { color: palette.green, fontWeight: '900' }, cardBody: { flex: 1, marginLeft: 12 }, cardTitle: { color: palette.ink, fontSize: 14, fontWeight: '800' }, cardMeta: { color: palette.muted, fontSize: 11, marginTop: 4 }, rolePill: { paddingHorizontal: 9, paddingVertical: 6, borderRadius: 10, backgroundColor: palette.mint }, roleText: { color: palette.green, fontSize: 9, fontWeight: '900', textTransform: 'uppercase' }, statusWarning: { color: palette.orange },
  empty: { alignItems: 'center', padding: 26, borderRadius: 18, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper }, emptyTitle: { color: palette.ink, fontSize: 17, fontWeight: '800', marginTop: 10 }, emptyText: { color: palette.muted, fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 5 },
  primaryButton: { minHeight: 52, borderRadius: 16, backgroundColor: palette.green, alignItems: 'center', justifyContent: 'center', marginTop: 18, paddingHorizontal: 18 }, primaryText: { color: palette.paper, fontWeight: '800', fontSize: 14 }, secondaryButton: { minHeight: 48, borderRadius: 15, borderWidth: 1, borderColor: palette.green, alignItems: 'center', justifyContent: 'center', marginTop: 10 }, secondaryText: { color: palette.green, fontWeight: '800' }, dangerButton: { minHeight: 48, borderRadius: 15, borderWidth: 1, borderColor: '#F0C7AD', backgroundColor: '#FFF3EA', alignItems: 'center', justifyContent: 'center', marginTop: 10 }, dangerText: { color: palette.orange, fontWeight: '800' },
  label: { color: palette.muted, fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 0.7, marginTop: 16, marginBottom: 7 }, input: { minHeight: 50, borderRadius: 14, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper, color: palette.ink, paddingHorizontal: 14, fontSize: 14 }, tokenInput: { minHeight: 90, paddingTop: 13, textAlignVertical: 'top' },
  roleCard: { padding: 13, borderRadius: 14, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper, marginBottom: 8 }, roleCardActive: { borderColor: palette.green, backgroundColor: palette.mint }, roleLabel: { color: palette.ink, fontSize: 13, fontWeight: '800' }, roleDescription: { color: palette.muted, fontSize: 11, lineHeight: 16, marginTop: 3 },
  tokenCard: { padding: 18, borderRadius: 18, backgroundColor: palette.mint, marginTop: 18 }, tokenLabel: { color: palette.green, fontSize: 10, fontWeight: '900', letterSpacing: 0.8, textTransform: 'uppercase' }, token: { color: palette.ink, fontFamily: 'Courier', fontSize: 13, lineHeight: 20, marginTop: 10 }, warning: { color: palette.orange, fontSize: 11, lineHeight: 17, marginTop: 10 },
  detailCard: { alignItems: 'center', padding: 24, borderRadius: 20, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper }, detailAvatar: { width: 72, height: 72, borderRadius: 24, backgroundColor: palette.mint, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }, detailName: { color: palette.ink, fontSize: 21, fontWeight: '800', marginTop: 12 }, detailMeta: { color: palette.muted, fontSize: 12, marginTop: 5 },
  inviteBanner: { padding: 18, borderRadius: 18, backgroundColor: palette.mint, marginBottom: 14 }, inviteTitle: { color: palette.green, fontSize: 18, fontWeight: '800' }, inviteText: { color: palette.muted, fontSize: 12, lineHeight: 18, marginTop: 5 }, error: { color: palette.orange, fontSize: 12, textAlign: 'center', marginTop: 10 },
});
