import { StyleSheet } from 'react-native';

import { palette } from '../../lib/design';

export const authGradient = [palette.authGradientStart, palette.authGradientEnd] as const;

export const styles = StyleSheet.create({
  background: { flex: 1 },
  safe: { flex: 1 },
  avoid: { flex: 1 },
  scroll: { flexGrow: 1, paddingHorizontal: 24, paddingTop: 62, paddingBottom: 30, alignItems: 'center' },
  center: { flex: 1, backgroundColor: palette.cream, alignItems: 'center', justifyContent: 'center' },
  logo: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-4deg' }],
  },
  brand: {
    marginTop: 14,
    color: palette.green,
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 2.2,
    textTransform: 'uppercase',
  },
  title: {
    marginTop: 30,
    color: palette.ink,
    fontSize: 31,
    lineHeight: 38,
    fontWeight: '800',
    textAlign: 'center',
  },
  subtitle: {
    marginTop: 12,
    maxWidth: 350,
    color: palette.muted,
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
  },
  card: {
    width: '100%',
    marginTop: 24,
    padding: 16,
    borderRadius: 18,
    backgroundColor: palette.paper,
    borderWidth: 1,
    borderColor: palette.line,
  },
  tabs: {
    height: 42,
    flexDirection: 'row',
    backgroundColor: palette.cream,
    borderRadius: 13,
    padding: 4,
    marginBottom: 16,
  },
  tab: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: 10 },
  tabActive: { backgroundColor: palette.paper, borderWidth: 1, borderColor: palette.line },
  tabText: { color: palette.muted, fontSize: 12, fontWeight: '800' },
  tabTextActive: { color: palette.green },
  label: {
    marginTop: 12,
    marginBottom: 7,
    color: palette.muted,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  input: {
    minHeight: 50,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 14,
    paddingHorizontal: 14,
    color: palette.ink,
    backgroundColor: palette.paper,
    fontSize: 15,
  },
  otpInput: { fontSize: 24, letterSpacing: 7, textAlign: 'center' },
  primary: {
    minHeight: 52,
    marginTop: 16,
    paddingHorizontal: 18,
    borderRadius: 16,
    backgroundColor: palette.green,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryText: { color: palette.paper, fontSize: 14, fontWeight: '800' },
  secondary: {
    minHeight: 48,
    marginTop: 10,
    paddingHorizontal: 16,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryText: { color: palette.green, fontSize: 13, fontWeight: '800', textAlign: 'center' },
  textButton: {
    minHeight: 44,
    marginTop: 8,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textButtonText: { color: palette.green, fontSize: 12, fontWeight: '800', textAlign: 'center' },
  disabled: { opacity: 0.55 },
  error: { marginTop: 12, color: palette.orange, fontSize: 12, lineHeight: 18, textAlign: 'center' },
  notice: { marginTop: 12, color: palette.green, fontSize: 12, lineHeight: 18, textAlign: 'center' },
  email: { marginTop: 8, color: palette.ink, fontSize: 15, fontWeight: '800', textAlign: 'center' },
  hint: { marginTop: 14, color: palette.muted, fontSize: 11, lineHeight: 17, textAlign: 'center' },
});
