import React, { useRef, useState } from 'react';
import { Alert, Pressable, SafeAreaView, ScrollView, Text, TextInput, View } from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { claimChallenge, confirmEarning, consumeRedemption } from '../api';
import { ClaimedChallenge, MenuChoice } from '../types';
import { rewardColors, rewardStyles as s } from '../styles';
import { RewardHeader } from './RewardUI';

export function LoyaltyScanner({menu,onBack}:{menu:MenuChoice[];onBack:()=>void}){
 const[permission,requestPermission]=useCameraPermissions();const[token,setToken]=useState('');const[claimed,setClaimed]=useState<ClaimedChallenge|null>(null);const[scanning,setScanning]=useState(false);const[busy,setBusy]=useState(false);const[amount,setAmount]=useState('');const[quantities,setQuantities]=useState<Record<string,number>>({});const[freeItems,setFreeItems]=useState<Record<string,boolean>>({});const requestKey=useRef(`loyalty-${Date.now()}-${Math.random().toString(36).slice(2)}`);
 const claim=async(value:string)=>{if(scanning||claimed)return;setScanning(true);try{setClaimed(await claimChallenge(value));}catch(caught){Alert.alert('Code rejected',caught instanceof Error?caught.message:'The code is invalid.');}finally{setScanning(false);}};
 if(!claimed)return <SafeAreaView style={s.safe}><RewardHeader title="Scan rewards code" onBack={onBack}/>{permission?.granted?<View style={{flex:1}}><CameraView style={s.camera} barcodeScannerSettings={{barcodeTypes:['qr']}} onBarcodeScanned={({data})=>void claim(data)}/><View style={s.scannerOverlay}><Text style={s.cardTitle}>One-time customer code</Text><Text style={s.meta}>Only a live, unused 60-second code can be claimed.</Text></View></View>:<ScrollView contentContainerStyle={s.scroll}><Text style={s.intro}>Camera access is used only to scan customer reward codes.</Text><Pressable onPress={requestPermission} style={s.primary}><Text style={s.primaryText}>Allow camera</Text></Pressable><Text style={s.sectionTitle}>Manual fallback</Text><TextInput autoCapitalize="none" value={token} onChangeText={setToken} style={s.field} placeholder="Paste one-time code"/><Pressable disabled={!token.trim()||scanning} onPress={()=>void claim(token)} style={[s.secondary,(!token.trim()||scanning)&&s.disabled]}><Text style={s.secondaryText}>Validate code</Text></Pressable></ScrollView>}</SafeAreaView>;
 const items=menu.filter(item=>(quantities[item.id]??0)>0).map(item=>({menuItemId:item.id,quantity:quantities[item.id],wasFree:Boolean(freeItems[item.id])}));
 const confirm=async()=>{setBusy(true);try{if(claimed.purpose==='earn'){const receipt=await confirmEarning(claimed.challengeId,{items,finalEligiblePence:Math.round(Number(amount||0)*100)},requestKey.current);Alert.alert('Progress issued',receipt.entries.length?receipt.entries.map(entry=>`+${entry.amount} ${entry.programName}`).join('\n'):'No joined programme matched this purchase.');}else{await consumeRedemption(claimed.challengeId,items,requestKey.current);Alert.alert('Reward validated','Apply the displayed benefit on the external till.');}onBack();}catch(caught){Alert.alert('Could not confirm',caught instanceof Error?caught.message:'Please try again.');}finally{setBusy(false);}};
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.scroll}><RewardHeader title={claimed.purpose==='earn'?'Verify purchase':'Validate redemption'} onBack={onBack}/><View style={s.card}><Text style={s.cardTitle}>{claimed.customerName}</Text><Text style={s.meta}>The one-time code is claimed by your staff session. Confirm only after checking the external-till purchase.</Text></View>{claimed.purpose==='earn'&&<><Text style={s.label}>Final eligible spend (£)</Text><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" style={s.field}/></>}<Text style={s.sectionTitle}>Qualifying basket</Text>{menu.map(item=><View key={item.id} style={s.card}><View style={s.row}><View style={{flex:1}}><Text style={s.cardTitle}>{item.name}</Text><Text style={s.meta}>{item.categoryName}</Text></View><Pressable accessibilityLabel={`Remove ${item.name}`} onPress={()=>setQuantities(all=>({...all,[item.id]:Math.max(0,(all[item.id]??0)-1)}))} style={s.iconButton}><Text>−</Text></Pressable><Text style={s.quantity}>{quantities[item.id]??0}</Text><Pressable accessibilityLabel={`Add ${item.name}`} onPress={()=>setQuantities(all=>({...all,[item.id]:Math.min(99,(all[item.id]??0)+1)}))} style={s.iconButton}><Text>+</Text></Pressable></View>{claimed.purpose==='earn'&&(quantities[item.id]??0)>0&&<Pressable onPress={()=>setFreeItems(all=>({...all,[item.id]:!all[item.id]}))} style={s.secondary}><Text style={s.secondaryText}>{freeItems[item.id]?'Free/redeemed · earns no item points':'Mark free or redeemed'}</Text></Pressable>}</View>)}<Pressable disabled={busy} onPress={confirm} style={[s.primary,busy&&s.disabled]}><Text style={s.primaryText}>{busy?'Confirming…':claimed.purpose==='earn'?'Issue verified progress':'Consume reward once'}</Text></Pressable><Text style={s.meta}>This creates an immutable audit record. It does not independently verify payment processed by the external till.</Text></ScrollView></SafeAreaView>;
}
