import { StyleSheet } from 'react-native';

import { palette } from '../../lib/design';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.cream },
  scroll: { padding: 20, paddingBottom: 48 },
  topRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  overline: {
    fontSize: 10,
    letterSpacing: 1.2,
    fontWeight: '900',
    color: palette.orange,
    textTransform: 'uppercase',
  },
  title: { marginTop: 4, fontSize: 28, lineHeight: 34, fontWeight: '800', color: palette.ink },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.mint,
  },
  avatarText: { color: palette.green, fontWeight: '900' },
  search: {
    minHeight: 52,
    marginTop: 20,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    backgroundColor: palette.paper,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 16,
  },
  searchInput: { flex: 1, color: palette.ink, fontSize: 14 },
  sectionTitle: { marginTop: 23, marginBottom: 12, color: palette.ink, fontSize: 18, fontWeight: '800' },
  card: {
    flexDirection: 'row',
    minHeight: 126,
    marginBottom: 12,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: palette.paper,
    borderWidth: 1,
    borderColor: palette.line,
  },
  cardImage: { width: 112, minHeight: 126 },
  cardBody: { flex: 1, padding: 14, justifyContent: 'center' },
  cardTitle: { color: palette.ink, fontSize: 17, fontWeight: '800' },
  category: {
    marginTop: 4,
    color: palette.green,
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  meta: { marginTop: 5, color: palette.muted, fontSize: 11, lineHeight: 16 },
  rating: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 7 },
  ratingText: { color: palette.ink, fontSize: 11, fontWeight: '800' },
  stateCard: {
    minHeight: 150,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
  },
  stateTitle: { marginTop: 10, color: palette.ink, fontSize: 16, fontWeight: '800', textAlign: 'center' },
  stateText: { marginTop: 6, color: palette.muted, fontSize: 12, lineHeight: 18, textAlign: 'center' },
  link: { marginTop: 10, color: palette.green, fontSize: 12, fontWeight: '800' },
  hero: { width: '100%', height: 260 },
  heroActions: {
    position: 'absolute',
    top: 14,
    left: 14,
    right: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,253,252,0.94)',
    borderWidth: 1,
    borderColor: palette.line,
  },
  detailBody: { padding: 20, paddingBottom: 50 },
  detailTitle: { color: palette.ink, fontSize: 29, lineHeight: 35, fontWeight: '800' },
  description: { marginTop: 12, color: palette.muted, fontSize: 14, lineHeight: 21 },
  actions: { flexDirection: 'row', gap: 9, marginTop: 18 },
  action: {
    flex: 1,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
  },
  actionText: { color: palette.green, fontSize: 10, fontWeight: '800' },
  section: { marginTop: 24 },
  sectionHeading: { marginBottom: 10, color: palette.ink, fontSize: 18, fontWeight: '800' },
  hoursRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
  },
  hoursText: { color: palette.muted, fontSize: 12 },
  menuCategory: {
    marginTop: 14,
    color: palette.green,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  menuItem: {
    minHeight: 80,
    flexDirection: 'row',
    gap: 11,
    alignItems: 'center',
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
  },
  menuImage: { width: 64, height: 64, borderRadius: 14 },
  menuCopy: { flex: 1 },
  menuName: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  menuDescription: { marginTop: 3, color: palette.muted, fontSize: 11, lineHeight: 16 },
  eventBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 4 },
  eventBadgeText: { color: palette.orange, fontSize: 11, lineHeight: 16, fontWeight: '800' },
  price: { color: palette.green, fontSize: 13, fontWeight: '900' },
  loadMore: { minHeight: 48, alignItems: 'center', justifyContent: 'center' },
  followButton: {
    minHeight: 50,
    marginTop: 16,
    borderRadius: 16,
    backgroundColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  followText: { color: palette.paper, fontSize: 13, fontWeight: '900' },
  disabled: { opacity: 0.45 },
});
