import { supabase } from '../../lib/supabase';
import { Order, OrderChannel, OrderStatus } from './types';

export async function createOrder(businessId:string,channel:OrderChannel,items:{menuItemId:string;quantity:number}[],idempotencyKey:string){const result=await supabase.rpc('create_trusted_order',{target_business_id:businessId,requested_channel:channel,requested_items:items,request_key:idempotencyKey});if(result.error)throw result.error;return getOrder(String(result.data.id));}
export async function getOrder(orderId:string){const result=await supabase.from('orders').select('*,order_items(*)').eq('id',orderId).single();if(result.error)throw result.error;return mapOrder(result.data as Record<string,unknown>);}
export async function listBusinessOrders(businessId:string){const result=await supabase.from('orders').select('*,order_items(*)').eq('business_id',businessId).order('created_at',{ascending:false}).limit(100);if(result.error)throw result.error;return (result.data as Record<string,unknown>[]).map(mapOrder);}
export async function listCustomerOrders(customerId:string){const result=await supabase.from('orders').select('*,order_items(*)').eq('customer_id',customerId).order('created_at',{ascending:false}).limit(50);if(result.error)throw result.error;return (result.data as Record<string,unknown>[]).map(mapOrder);}
export async function updateOrderStatus(orderId:string,status:OrderStatus,reason?:string){const result=await supabase.rpc('update_order_fulfilment',{target_order_id:orderId,next_status:status,reason:reason??null});if(result.error)throw result.error;return getOrder(orderId);}
export async function cancelUnpaidOrder(orderId:string){const result=await supabase.rpc('cancel_unpaid_order',{target_order_id:orderId});if(result.error)throw result.error;return getOrder(orderId);}
function mapOrder(row:Record<string,unknown>):Order{const raw=Array.isArray(row.order_items)?row.order_items as Record<string,unknown>[]:[];return{id:String(row.id),businessId:String(row.business_id),locationId:String(row.location_id),customerId:row.customer_id?String(row.customer_id):null,createdBy:String(row.created_by),channel:row.channel as Order['channel'],status:row.status as Order['status'],paymentStatus:row.payment_status as Order['paymentStatus'],currency:'GBP',subtotalPence:Number(row.subtotal_pence),totalPence:Number(row.total_pence),refundedPence:Number(row.refunded_pence),confirmationDeadline:row.confirmation_deadline?String(row.confirmation_deadline):null,cancellationReason:row.cancellation_reason?String(row.cancellation_reason):null,createdAt:String(row.created_at),updatedAt:String(row.updated_at),items:raw.map(item=>({id:String(item.id),menuItemId:item.menu_item_id?String(item.menu_item_id):null,name:String(item.name),quantity:Number(item.quantity),unitPricePence:Number(item.unit_price_pence),lineTotalPence:Number(item.line_total_pence) }))};}
