import { StyleSheet } from 'react-native';

import { palette } from '../../lib/design';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.cream },
  fill: { flex: 1 },
  scroll: { padding: 20, paddingBottom: 48 },
  header: { flexDirection: 'row', alignItems: 'center', marginBottom: 18 },
  back: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.paper,
    borderWidth: 1,
    borderColor: palette.line,
  },
  headerCopy: { flex: 1, marginLeft: 12 },
  overline: {
    color: palette.orange,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  title: { color: palette.ink, fontSize: 24, fontWeight: '900', marginTop: 2 },
  intro: { color: palette.muted, fontSize: 12, lineHeight: 18, marginBottom: 14 },
  statusCard: {
    padding: 16,
    borderRadius: 18,
    backgroundColor: palette.mint,
    borderWidth: 1,
    borderColor: palette.line,
    marginBottom: 14,
  },
  statusTitle: { color: palette.green, fontSize: 15, fontWeight: '900' },
  statusText: { color: palette.muted, fontSize: 12, lineHeight: 18, marginTop: 5 },
  warningCard: {
    padding: 14,
    borderRadius: 16,
    backgroundColor: palette.warningPaper,
    borderWidth: 1,
    borderColor: palette.warningLine,
    marginBottom: 14,
  },
  warningTitle: { color: palette.orange, fontWeight: '900', fontSize: 13 },
  warningText: { color: palette.ink, fontSize: 12, lineHeight: 18, marginTop: 4 },
  section: {
    padding: 16,
    borderRadius: 18,
    backgroundColor: palette.paper,
    borderWidth: 1,
    borderColor: palette.line,
    marginBottom: 12,
  },
  sectionTitle: { color: palette.ink, fontSize: 17, fontWeight: '900', marginBottom: 4 },
  sectionHint: { color: palette.muted, fontSize: 11, lineHeight: 17, marginBottom: 10 },
  label: {
    color: palette.muted,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    marginTop: 11,
    marginBottom: 6,
  },
  input: {
    minHeight: 49,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 14,
    backgroundColor: palette.nearWhite,
    color: palette.ink,
    paddingHorizontal: 13,
    fontSize: 14,
  },
  multilineInput: { minHeight: 82, paddingTop: 12, textAlignVertical: 'top' },
  disabled: { backgroundColor: palette.disabledPaper, color: palette.muted },
  entityGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  entityOption: {
    minHeight: 44,
    paddingHorizontal: 12,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: palette.line,
    justifyContent: 'center',
    backgroundColor: palette.nearWhite,
  },
  entityActive: { borderColor: palette.green, backgroundColor: palette.mint },
  entityText: { color: palette.ink, fontSize: 11, fontWeight: '800' },
  entityTextActive: { color: palette.green },
  switchRow: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  switchCopy: { flex: 1, paddingRight: 12 },
  switchTitle: { color: palette.ink, fontSize: 13, fontWeight: '800' },
  switchHint: { color: palette.muted, fontSize: 11, marginTop: 3 },
  error: { color: palette.orange, fontSize: 12, lineHeight: 18, marginBottom: 10 },
  action: {
    minHeight: 52,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
    marginTop: 10,
    paddingHorizontal: 16,
  },
  secondary: { backgroundColor: palette.paper, borderWidth: 1, borderColor: palette.green },
  danger: { backgroundColor: palette.warningPaper, borderWidth: 1, borderColor: palette.warningLine },
  actionDisabled: { opacity: 0.45 },
  actionText: { color: palette.paper, fontSize: 14, fontWeight: '900' },
  secondaryText: { color: palette.green },
  dangerText: { color: palette.orange },
  attestation: { minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 8 },
  checkbox: {
    width: 26,
    height: 26,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.paper,
  },
  checkboxActive: { backgroundColor: palette.green },
  attestationText: { flex: 1, color: palette.ink, fontSize: 12, lineHeight: 18 },
  state: { minHeight: 220, alignItems: 'center', justifyContent: 'center', padding: 24 },
  stateText: { color: palette.muted, textAlign: 'center', lineHeight: 20, marginTop: 10 },
});
