import { HttpError, json, paypalRequest, required, serviceClient, stripeRequest } from '../_shared/payments.ts';

type Job={id:string;type:'expire_order'|'refund'|'reconcile';order_id:string|null;refund_id:string|null;attempts:number};

Deno.serve(async(request)=>{if(request.headers.get('x-cron-secret')!==Deno.env.get('PAYMENT_CRON_SECRET'))return json({error:'Unauthorized'},401);try{const db=serviceClient();const claimed=await db.rpc('claim_payment_jobs',{batch_size:25});if(claimed.error)throw claimed.error;const results=[];for(const job of (claimed.data??[]) as Job[]){try{if(job.type==='expire_order')await expireOrder(job);else if(job.type==='refund')await refund(job);else await reconcile(job);await complete(job.id);results.push({id:job.id,status:'completed'});}catch(error){await fail(job,error);results.push({id:job.id,status:'retrying'});}}return json({processed:results.length,results});}catch(error){console.error(error);return json({error:error instanceof Error?error.message:'Payment jobs failed.'},500);}});

async function expireOrder(job:Job){if(!job.order_id)return;const db=serviceClient();const order=await db.from('orders').select('*').eq('id',job.order_id).maybeSingle();if(!order.data||order.data.status!=='needs_confirmation'||new Date(order.data.confirmation_deadline)>new Date())return;await db.from('orders').update({status:'refund_pending',payment_status:'refund_pending',cancellation_reason:'Shop did not confirm within 10 minutes',updated_at:new Date().toISOString()}).eq('id',job.order_id).eq('status','needs_confirmation');await db.from('payment_jobs').upsert({type:'refund',order_id:job.order_id,status:'pending',run_at:new Date().toISOString(),idempotency_key:`timeout-refund:${job.order_id}`},{onConflict:'idempotency_key'});}

async function refund(job:Job){const db=serviceClient();let refundRow;if(job.refund_id){refundRow=await db.from('payment_refunds').select('*').eq('id',job.refund_id).single();}else{const order=await db.from('orders').select('*').eq('id',job.order_id).single();const attempt=await db.from('payment_attempts').select('*').eq('order_id',job.order_id).in('status',['succeeded','partially_refunded']).order('succeeded_at',{ascending:false}).limit(1).single();if(!order.data||!attempt.data)throw new Error('Refundable payment not found.');refundRow=await db.from('payment_refunds').upsert({order_id:order.data.id,payment_attempt_id:attempt.data.id,amount_pence:order.data.total_pence-order.data.refunded_pence,reason:order.data.cancellation_reason??'Order cancelled',status:'pending',idempotency_key:`automatic:${order.data.id}`},{onConflict:'payment_attempt_id,idempotency_key'}).select().single();}
  const refund=refundRow.data;if(refundRow.error||!refund)throw refundRow.error??new Error('Refund not found.');if(refund.status==='succeeded')return;const attempt=await db.from('payment_attempts').select('*,orders(business_id,total_pence,refunded_pence)').eq('id',refund.payment_attempt_id).single();if(!attempt.data)throw new Error('Payment attempt not found.');const connection=await db.from('payment_connections').select('*').eq('business_id',attempt.data.orders.business_id).eq('provider',attempt.data.provider).eq('status','ready').single();if(!connection.data)throw new Error('Provider connection unavailable.');await db.from('payment_refunds').update({status:'processing',updated_at:new Date().toISOString()}).eq('id',refund.id);let providerId='';if(attempt.data.provider==='stripe'){const body=new URLSearchParams({payment_intent:attempt.data.provider_intent_id,amount:String(refund.amount_pence)});const result=await stripeRequest('/refunds',{method:'POST',body,account:connection.data.provider_account_id,idempotencyKey:`refund:${refund.id}`});providerId=String(result.id);}else{const result=await paypalRequest(`/v2/payments/captures/${attempt.data.provider_capture_id}/refund`,{method:'POST',idempotencyKey:`refund:${refund.id}`,body:{amount:{currency_code:'GBP',value:(refund.amount_pence/100).toFixed(2)},note_to_payer:refund.reason}});providerId=String(result.id);}
  const refunded=attempt.data.orders.refunded_pence+refund.amount_pence;const full=refunded>=attempt.data.orders.total_pence;await db.from('payment_refunds').update({status:'succeeded',provider_refund_id:providerId,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',refund.id);await db.from('payment_attempts').update({status:full?'refunded':'partially_refunded',updated_at:new Date().toISOString()}).eq('id',attempt.data.id);const orderUpdate:Record<string,unknown>={refunded_pence:refunded,payment_status:full?'refunded':'partially_refunded',updated_at:new Date().toISOString()};if(full)orderUpdate.status='refunded';await db.from('orders').update(orderUpdate).eq('id',refund.order_id);
}
async function reconcile(job:Job){if(!job.order_id)return;const db=serviceClient();const attempt=await db.from('payment_attempts').select('*,orders(channel)').eq('order_id',job.order_id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(!attempt.data||attempt.data.status==='succeeded')return;if(attempt.data.provider==='stripe'&&attempt.data.provider_intent_id){const connection=await db.from('payment_connections').select('provider_account_id').eq('business_id',(await db.from('orders').select('business_id').eq('id',job.order_id).single()).data?.business_id).eq('provider','stripe').single();const intent=await stripeRequest(`/payment_intents/${attempt.data.provider_intent_id}`,{account:connection.data?.provider_account_id});if(intent.status==='succeeded')await db.from('payment_attempts').update({status:'succeeded',succeeded_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',attempt.data.id);}}
async function complete(id:string){await serviceClient().from('payment_jobs').update({status:'completed',lease_until:null,updated_at:new Date().toISOString()}).eq('id',id);}
async function fail(job:Job,error:unknown){const terminal=job.attempts>=8;await serviceClient().from('payment_jobs').update({status:terminal?'failed':'pending',lease_until:null,run_at:new Date(Date.now()+Math.min(60,2**job.attempts)*60000).toISOString(),last_error:String(error).slice(0,500),updated_at:new Date().toISOString()}).eq('id',job.id);}
