import { StyleSheet } from 'react-native';

export const colors = {
  ink: '#241A16', muted: '#766A63', cream: '#F7F2EA', paper: '#FFFDFC', green: '#235C4B',
  mint: '#DDEBE4', orange: '#D9773E', line: '#E9E0D7',
};

export const styles = StyleSheet.create({
  flex: { flex: 1 }, safe: { flex: 1, backgroundColor: colors.cream }, scroll: { padding: 20, paddingBottom: 48 }, center: { flex: 1, padding: 28, alignItems: 'center', justifyContent: 'center' },
  header: { flexDirection: 'row', alignItems: 'center', marginBottom: 18 }, headerTitle: { flex: 1, textAlign: 'center', fontSize: 20, fontWeight: '800', color: colors.ink }, iconButton: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' }, iconSpacer: { width: 42 },
  lead: { color: colors.muted, fontSize: 14, lineHeight: 21, marginBottom: 12 }, field: { marginTop: 14 }, label: { marginBottom: 7, color: colors.muted, fontSize: 11, fontWeight: '800', letterSpacing: 0.7, textTransform: 'uppercase' },
  input: { minHeight: 50, paddingHorizontal: 14, borderWidth: 1, borderColor: colors.line, borderRadius: 14, backgroundColor: colors.paper, color: colors.ink, fontSize: 15 }, multiline: { minHeight: 94, paddingTop: 13, textAlignVertical: 'top' }, inputDisabled: { backgroundColor: '#EEE9E2', color: colors.muted },
  primaryButton: { minHeight: 52, borderRadius: 16, backgroundColor: colors.green, marginTop: 20, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 }, primaryButtonWide: { width: '100%', minHeight: 52, borderRadius: 16, backgroundColor: colors.green, marginTop: 22, alignItems: 'center', justifyContent: 'center' }, primaryText: { color: colors.paper, fontSize: 14, fontWeight: '800' },
  secondaryButton: { minHeight: 50, borderRadius: 16, borderWidth: 1, borderColor: colors.green, marginTop: 10, alignItems: 'center', justifyContent: 'center' }, secondaryButtonWide: { width: '100%', minHeight: 50, borderRadius: 16, borderWidth: 1, borderColor: colors.green, marginTop: 10, alignItems: 'center', justifyContent: 'center' }, secondaryText: { color: colors.green, fontWeight: '800', fontSize: 13 },
  declaration: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 18 }, warningCard: { padding: 16, borderRadius: 16, backgroundColor: '#FFF3EA', borderWidth: 1, borderColor: '#F0C7AD', marginBottom: 4 }, warningTitle: { color: colors.orange, fontWeight: '800', fontSize: 14 }, warningText: { color: colors.ink, marginTop: 5, lineHeight: 19 },
  statusHero: { alignItems: 'center', backgroundColor: colors.paper, borderRadius: 22, borderWidth: 1, borderColor: colors.line, padding: 28, marginTop: 12 }, statusIcon: { width: 58, height: 58, borderRadius: 20, backgroundColor: colors.mint, alignItems: 'center', justifyContent: 'center' }, statusTitle: { marginTop: 15, color: colors.ink, fontSize: 23, fontWeight: '800', textAlign: 'center' }, statusText: { color: colors.muted, fontSize: 14, lineHeight: 21, textAlign: 'center', marginTop: 8 }, summaryCard: { backgroundColor: colors.paper, borderRadius: 18, borderWidth: 1, borderColor: colors.line, padding: 16, marginTop: 16 }, summaryRow: { paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.line }, summaryLabel: { color: colors.muted, fontSize: 10, fontWeight: '800', textTransform: 'uppercase' }, summaryValue: { color: colors.ink, fontSize: 14, fontWeight: '700', marginTop: 4 },
  topRow: { flexDirection: 'row', alignItems: 'center' }, topTitle: { flex: 1, paddingHorizontal: 12 }, overline: { color: colors.orange, fontSize: 10, fontWeight: '800', letterSpacing: 1, textTransform: 'uppercase' }, pageTitle: { color: colors.ink, fontSize: 24, fontWeight: '800', marginTop: 3 }, rolePill: { paddingHorizontal: 10, paddingVertical: 7, borderRadius: 12, backgroundColor: colors.mint }, roleText: { color: colors.green, fontSize: 10, fontWeight: '800', textTransform: 'uppercase' },
  hero: { borderRadius: 22, padding: 20, marginTop: 22 }, heroOverline: { color: '#BFD7CE', fontSize: 10, fontWeight: '800', letterSpacing: 1.2 }, heroValue: { color: colors.paper, fontSize: 28, fontWeight: '800', marginTop: 7 }, heroHint: { color: '#D8E6E0', fontSize: 12, marginTop: 10 }, progress: { height: 7, backgroundColor: '#4D786B', borderRadius: 4, overflow: 'hidden', marginTop: 14 }, progressFill: { height: 7, backgroundColor: colors.paper },
  stateCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16, backgroundColor: colors.paper, borderRadius: 17, borderWidth: 1, borderColor: colors.line, marginTop: 14 }, cardTitle: { color: colors.ink, fontWeight: '800', fontSize: 14 }, cardText: { color: colors.muted, fontSize: 11, marginTop: 4 }, statePill: { paddingHorizontal: 10, paddingVertical: 7, borderRadius: 10, backgroundColor: '#F6E3D6' }, livePill: { backgroundColor: colors.mint }, stateText: { color: colors.green, fontSize: 9, fontWeight: '900', letterSpacing: 0.8 },
  sectionTitle: { color: colors.ink, fontSize: 18, fontWeight: '800', marginTop: 26, marginBottom: 12 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, actionCard: { width: '48.5%', padding: 15, backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.line, borderRadius: 16, flexDirection: 'row', alignItems: 'center' }, actionIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: colors.mint, alignItems: 'center', justifyContent: 'center' }, actionText: { color: colors.ink, fontWeight: '800', fontSize: 12, marginLeft: 10, flex: 1 }, readOnly: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 18 },
  hoursRow: { flexDirection: 'row', alignItems: 'center', minHeight: 64, paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: colors.line }, hoursDay: { width: 88 }, timeInputs: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center' }, timeInput: { width: 56, height: 38, borderWidth: 1, borderColor: colors.line, borderRadius: 10, backgroundColor: colors.paper, color: colors.ink, textAlign: 'center', fontSize: 12 }, timeDash: { color: colors.muted, marginHorizontal: 4 },
  publishRow: { flexDirection: 'row', alignItems: 'center', marginTop: 20, padding: 16, borderRadius: 16, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.paper }, publishCopy: { flex: 1, paddingRight: 12 }, signOut: { height: 48, borderWidth: 1, borderColor: '#F0C7AD', borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginTop: 28, flexDirection: 'row', gap: 7, backgroundColor: '#FFF7F2' }, signOutText: { color: colors.orange, fontWeight: '800', fontSize: 13 }, loadingText: { color: colors.green, fontSize: 13, fontWeight: '700', marginTop: 14 },
  headerMedia: { height: 150, borderRadius: 18, backgroundColor: colors.mint, borderWidth: 1, borderColor: colors.line, overflow: 'hidden', alignItems: 'center', justifyContent: 'center', marginTop: 8 }, logoMedia: { width: 78, height: 78, borderRadius: 24, backgroundColor: colors.mint, borderWidth: 4, borderColor: colors.cream, marginTop: -32, marginLeft: 16, overflow: 'hidden', alignItems: 'center', justifyContent: 'center' }, mediaImage: { width: '100%', height: '100%' }, mediaBadge: { position: 'absolute', right: 10, bottom: 10, backgroundColor: 'rgba(36,26,22,0.78)', paddingHorizontal: 10, paddingVertical: 7, borderRadius: 10 }, mediaBadgeText: { color: colors.paper, fontSize: 10, fontWeight: '800' }, logoEdit: { position: 'absolute', right: 3, bottom: 3, width: 25, height: 25, borderRadius: 9, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center' },
  adminIntro: { padding: 18, borderRadius: 18, backgroundColor: colors.mint, marginBottom: 14 }, adminIntroTitle: { color: colors.green, fontSize: 18, fontWeight: '800' }, adminIntroText: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 5 }, reviewCard: { padding: 16, borderRadius: 17, backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.line, marginBottom: 10 }, reviewCardTop: { flexDirection: 'row', alignItems: 'center' }, reviewName: { flex: 1, color: colors.ink, fontSize: 15, fontWeight: '800' }, reviewStatus: { color: colors.orange, fontSize: 9, fontWeight: '900', textTransform: 'uppercase' }, reviewMeta: { color: colors.muted, fontSize: 12, marginTop: 6 }, emptyCard: { alignItems: 'center', padding: 28, borderRadius: 18, backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.line }, decisionRow: { flexDirection: 'row', gap: 10, marginTop: 18 }, approveButton: { flex: 1, minHeight: 50, borderRadius: 15, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center' }, rejectButton: { flex: 1, minHeight: 50, borderRadius: 15, backgroundColor: '#FFF3EA', borderWidth: 1, borderColor: '#F0C7AD', alignItems: 'center', justifyContent: 'center' }, rejectText: { color: colors.orange, fontWeight: '800' }, detailSection: { marginTop: 18, padding: 16, borderRadius: 17, backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.line }, detailTitle: { color: colors.ink, fontSize: 13, fontWeight: '800', marginBottom: 8 }, detailText: { color: colors.muted, fontSize: 13, lineHeight: 20 },
});
